Repository CS4850Group5A/VirtuDoc, pull requests merged in 2022-02, with the labels that each got.

#51 Fixed Web container crash on boot
  Dockerfile
  docker-entrypoint.sh
Labels: bug, DevOps

#62 Tag Images in Dev Stack
  docker-compose.yml
Labels: bug, DevOps

#65 Automatic Version Bumping
  .github/dependabot.yml
  pom.xml
Labels: enhancement, DevOps

#64 Screenshot captures during GHA tests
  .github/workflows/build.yml
  pom.xml
  src/test/java/com/virtudoc/web/E2EWalkthroughTest.java
  src/test/java/com/virtudoc/web/SampleE2ETest.java
Labels: enhancement, DevOps

#44 Test Dev Stack on GitHub Actions
  .github/workflows/build.yml
  cicd/dev/.rspec
  cicd/dev/Gemfile
  cicd/dev/Gemfile.lock
  cicd/dev/spec/email_spec.rb
  cicd/dev/spec/proxy_spec.rb
  cicd/dev/spec/spec_helper.rb
  cicd/dev/spec/web_spec.rb
  proxy/01-generate-certs.sh
  proxy/proxy.Dockerfile
  src/main/java/com/virtudoc/web/configuration/SecurityConfiguration.java
  src/main/java/com/virtudoc/web/controller/DebugController.java
Labels: enhancement, DevOps

#94 Fixed crash on application reboot
  src/main/java/com/virtudoc/web/runner/DatabaseSeedRunner.java
Labels: bug, DevOps

#96 Javadoc on GitHub Pages
  .github/workflows/javadoc.yml
  pom.xml
Labels: documentation, enhancement, DevOps

#97 Fixed YAML validation errors
  .github/workflows/javadoc.yml
Labels: bug, DevOps

#109 CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement, DevOps

#117 Redirect to login page
  src/main/java/com/virtudoc/web/controller/HomeController.java
Labels: enhancement

#125 Better dev stack logging
  dev/elk/filebeat.yml
  dev/elk/logstash/pipeline/logstash.conf
  docker-compose.yml
  src/main/resources/application.yml
Labels: enhancement, DevOps

#135 Static file hosting fixes
  src/main/java/com/virtudoc/web/configuration/SecurityConfiguration.java
  src/main/resources/static/img/doctors_symbol.png
  src/main/resources/static/img/logo.png
  src/main/resources/static/img/placeholder.png
  src/main/resources/templates/AppointmentCreation.html
  src/main/resources/templates/admin_records.html
  src/main/resources/templates/appointment.html
  src/main/resources/templates/current_appointments.html
  src/main/resources/templates/doctors_records.html
  src/main/resources/templates/login.html
  src/main/resources/templates/message.html
  src/main/resources/templates/patient_records.html
  src/main/resources/templates/register.html
  src/main/resources/templates/video.html
  src/test/java/com/virtudoc/web/StaticAssetTests.java
Labels: bug, DevOps

#159 Container Healthchecks
  docker-compose.yml
  src/main/java/com/virtudoc/web/controller/DebugController.java
  src/test/java/com/virtudoc/web/HealthEndpointTests.java
Labels: enhancement, DevOps

#173 Database primary key generation refactor
  src/main/java/com/virtudoc/web/configuration/SecurityConfiguration.java
  src/main/java/com/virtudoc/web/controller/SampleEntityController.java
  src/main/java/com/virtudoc/web/entity/Appointment.java
  src/main/java/com/virtudoc/web/entity/FileEntity.java
  src/main/java/com/virtudoc/web/entity/Role.java
  src/main/java/com/virtudoc/web/entity/SampleEntity.java
  src/main/java/com/virtudoc/web/entity/UserAccount.java
  src/main/java/com/virtudoc/web/repository/SampleEntityRepository.java
  src/main/java/com/virtudoc/web/runner/DatabaseSeedRunner.java
  src/test/java/com/virtudoc/web/JPASmokeTests.java
  src/test/java/com/virtudoc/web/SampleEntityControllerTests.java
Labels: bug, Backend

#176 Navbar th
  src/main/java/com/virtudoc/web/controller/appointmentController.java
  src/main/resources/templates/AppointmentCreation.html
  src/main/resources/templates/admin_records.html
  src/main/resources/templates/appointment.html
  src/main/resources/templates/current_appointments.html
  src/main/resources/templates/doctors_records.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/message.html
  src/main/resources/templates/patient_records.html
  src/main/resources/templates/video.html
Labels: enhancement, Frontend

#179 Helper method for currently logged-in user
  src/main/java/com/virtudoc/web/runner/MockUserSeeder.java
  src/main/java/com/virtudoc/web/service/AuthenticationService.java
Labels: enhancement, Backend
