Repository CS4850Group5A/VirtuDoc, pull requests merged in 2022-03, with the labels that each got.

#49 Container vulnerability scanning
  .github/workflows/snyk-container-analysis.yml
Labels: enhancement, DevOps

#186 Fixed ApplicationContext failures in bare-metal mode
  src/main/java/com/virtudoc/web/configuration/CloudConfiguration.java
  src/main/java/com/virtudoc/web/entity/Role.java
  src/main/resources/application.yml
Labels: bug, DevOps

#183 File ownership and ACL blocking
  src/main/java/com/virtudoc/web/entity/FileEntity.java
  src/main/java/com/virtudoc/web/exception/FileAccessNotPermitted.java
  src/main/java/com/virtudoc/web/service/FileService.java
  src/test/java/com/virtudoc/web/FileServiceTest.java
Labels: enhancement, Backend

#187 #181 Landing page POC
  src/main/java/com/virtudoc/web/controller/HomeController.java
  src/main/resources/static/img/doctors_symbol_invert.png
  src/main/resources/static/img/landing-backdrop.png
  src/main/resources/templates/index.html
  src/main/resources/templates/landing.html
Labels: enhancement, help wanted, proposal, Frontend

#184 User Account (made some changes)
  src/main/java/com/virtudoc/web/configuration/SecurityConfiguration.java
  src/main/java/com/virtudoc/web/controller/UserAccountController.java
  src/main/java/com/virtudoc/web/entity/UserAccount.java
  src/main/resources/static/img/mail_sent.png
  src/main/resources/templates/HIPAA_consent.html
  src/main/resources/templates/checkEmail.html
  src/main/resources/templates/mail/welcome.html
  src/main/resources/templates/register.html
Labels: enhancement, Frontend

#191 Switch to slim JRE/JDK images
  Dockerfile
  prod.Dockerfile
Labels: enhancement, DevOps

#192 Email link helper
  src/main/java/com/virtudoc/web/configuration/TemplateConfiguration.java
  src/main/java/com/virtudoc/web/rendering/dialect/EmailDialect.java
  src/main/java/com/virtudoc/web/rendering/processor/EmailLinkProcessor.java
  src/main/resources/application.yml
  src/main/resources/templates/mail/welcome.html
  src/main/resources/templates/test/imginjection.html
  src/main/resources/templates/test/imginjection2.html
  src/main/resources/templates/test/linkinjection.html
  src/main/resources/templates/test/linkinjection2.html
  src/test/java/com/virtudoc/web/EmailDialectTests.java
Labels: enhancement, Backend

#193 LiveReload
  pom.xml
  src/main/resources/application.yml
Labels: enhancement, DevOps

#194 Forgot Password
  src/main/java/com/virtudoc/web/configuration/SecurityConfiguration.java
  src/main/java/com/virtudoc/web/controller/UserAccountController.java
  src/main/resources/templates/forgotMyPassword.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mail/resetEmail.html
  src/main/resources/templates/newPassword.html
Labels: enhancement, Frontend

#196 Favicon
  src/main/java/com/virtudoc/web/configuration/SecurityConfiguration.java
  src/main/resources/static/android-chrome-192x192.png
  src/main/resources/static/android-chrome-512x512.png
  src/main/resources/static/apple-touch-icon.png
  src/main/resources/static/favicon-16x16.png
  src/main/resources/static/favicon-32x32.png
  src/main/resources/static/favicon.ico
  src/main/resources/static/site.webmanifest
  src/test/java/com/virtudoc/web/FaviconAssetTests.java
Labels: enhancement, Frontend

#203 Mobile layout for registration form
  src/main/resources/templates/register.html
Labels: enhancement, Frontend

#202 Fixed dying WebSocket connections
  proxy/nginx.conf
Labels: bug, DevOps

#212 Removed JUnit 4 dependency
  pom.xml
Labels: bug, DevOps

#213 Fixed blocked route to appointment pages
  src/main/java/com/virtudoc/web/configuration/SecurityConfiguration.java
  src/test/java/com/virtudoc/web/E2EWalkthroughTest.java
Labels: bug, Backend

#232 Temporary fix for serialization RCE CVE
  src/main/java/com/virtudoc/web/controller/GlobalControllerAdvice.java
Labels: bug, DevOps

#233 Reduce Snyk API calls
  .github/workflows/snyk-container-analysis.yml
Labels: bug, DevOps
